#!/usr/bin/env bun
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stringify } from 'yaml'
import { RESUME_DATA } from '../src/data/resume-data'
import { CONTACT } from '../src/data/social-bar'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DEFAULT_OUT = resolve(__dirname, 'cv.yaml')

function buildCv() {
  return {
    cv: {
      name: RESUME_DATA.name,
      location: RESUME_DATA.location,
      email: CONTACT.email,
      website: RESUME_DATA.personalWebsiteUrl,
      social_networks: [
        { network: 'GitHub', username: CONTACT.github },
        { network: 'LinkedIn', username: CONTACT.linkedin }
      ],
      sections: {
        summary: [RESUME_DATA.summary],
        experience: RESUME_DATA.work.map((w) => ({
          company: w.company,
          position: w.badges.length > 0 ? `${w.title} (${w.badges.join(', ')})` : w.title,
          start_date: w.start,
          end_date: w.end,
          highlights: w.highlights
        })),
        education: RESUME_DATA.education.map((e) => ({
          institution: e.school,
          area: e.degree,
          start_date: e.start,
          end_date: e.end
        })),
        projects: RESUME_DATA.projects.map((p) => {
          const META_TAGS = new Set(['Side Project', 'Open Source', 'Contract Work'])
          const tech = p.techStack.filter((t) => !META_TAGS.has(t))
          return {
            name: `[${p.title}](${p.link.href})`,
            summary: `${p.description}. *${tech.join(', ')}*`,
            highlights: []
          }
        }),
        skills: RESUME_DATA.skills
      }
    },
    design: {
      theme: 'engineeringresumes',
      page: {
        size: 'us-letter',
        top_margin: '0.4in',
        bottom_margin: '0.4in',
        left_margin: '0.55in',
        right_margin: '0.55in',
        show_top_note: false
      },
      section_titles: {
        space_above: '0.25cm',
        space_below: '0.1cm'
      },
      sections: {
        space_between_regular_entries: '0.1cm',
        space_between_text_based_entries: '0.05cm'
      }
    }
  }
}

export function buildResumeYaml(): string {
  return `# Generated by resume/export.ts — edit the source data, not this file.\n${stringify(buildCv())}`
}

export function exportResumeYaml(outPath: string = DEFAULT_OUT): string {
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, buildResumeYaml())
  return outPath
}

if (import.meta.main) {
  const out = exportResumeYaml()
  console.log(`wrote ${out}`)
}
