/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as HomeCvRouteImport } from './routes/_home/cv'
import { Route as HomeAboutRouteImport } from './routes/_home/about'

const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeCvRoute = HomeCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof HomeAboutRoute
  '/cv': typeof HomeCvRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof HomeAboutRoute
  '/cv': typeof HomeCvRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/_home/about': typeof HomeAboutRoute
  '/_home/cv': typeof HomeCvRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/cv' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/cv' | '/'
  id: '__root__' | '/_home' | '/_home/about' | '/_home/cv' | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/cv': {
      id: '/_home/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof HomeCvRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeCvRoute: typeof HomeCvRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeCvRoute: HomeCvRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
